# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"exists": "00_core.ipynb",
         "Comp": "00_core.ipynb",
         "DummyRun": "00_core.ipynb",
         "Image": "mif.ipynb",
         "load_mrtrix": "mif.ipynb",
         "save_mrtrix": "mif.ipynb",
         "warpconvert_fsl2mrtrix": "reg.ipynb",
         "sh2power": "sh.ipynb",
         "sh2spectrum": "sh.ipynb",
         "sh2RISH": "sh.ipynb",
         "amp2shellagg": "sh.ipynb",
         "amp2mssh": "sh.ipynb",
         "get_turbo_cm": "vis.ipynb",
         "plot_dirs": "vis.ipynb",
         "response_to_r": "vis.ipynb",
         "polarplotstyle": "vis.ipynb",
         "loadrf": "vis.ipynb",
         "plot_responses": "vis.ipynb",
         "ntheta": "vis.ipynb",
         "theta_1d": "vis.ipynb",
         "phi_1d": "vis.ipynb",
         "xyz_2d": "vis.ipynb",
         "plot_response_coef": "vis.ipynb",
         "MidpointNormalize": "vis.ipynb",
         "showimg": "vis.ipynb",
         "plots": "vis.ipynb"}

modules = ["core.py",
           "utils/mif.py",
           "reg.py",
           "sh.py",
           "utils/vis.py"]

doc_url = "https://maxpietsch.github.io/mrtrix3nb/"

git_url = "https://github.com/maxpietsch/mrtrix3nb/tree/master/"

def custom_doc_links(name): return None
