# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"plot_dirs": "utils.ipynb"}

modules = ["utils.py"]

doc_url = "https://maxpietsch.github.io/mrtrix3nb/"

git_url = "https://github.com/maxpietsch/mrtrix3nb/tree/master/"

def custom_doc_links(name): return None
