# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Comp": "00_core.ipynb",
         "warpconvert_fsl2mrtrix": "reg.ipynb",
         "plot_dirs": "utils.ipynb"}

modules = ["core.py",
           "reg.py",
           "utils/vis.py"]

doc_url = "https://maxpietsch.github.io/mrtrix3nb/"

git_url = "https://github.com/maxpietsch/mrtrix3nb/tree/master/"

def custom_doc_links(name): return None
