# AUTOGENERATED! DO NOT EDIT! File to edit: reg.ipynb (unless otherwise specified).

__all__ = ['warpconvert_fsl2mrtrix']

# Cell
def warpconvert_fsl2mrtrix(fslwarp, mrtrixwarp, fsl_in, fsl_ref, fsl_in_strides='+1,+2,+3', force=''):
    cmds = []
    cmds.append(f'mrconvert {fsl_in} -stride {fsl_in_strides} <TMP>/source.nii -force')
    cmds.append(f'warpinit <TMP>/source.nii <TMP>/identity_warp.nii -force')
    cmds.append(f'/usr/share/fsl/5.0/bin/applywarp --ref={fsl_ref} --in=<TMP>/identity_warp.nii --warp={fslwarp} --out=<TMP>/warp.nii.gz')
    cmds.append(f'warpcorrect <TMP>/warp.nii.gz {mrtrixwarp} ' + force)
    return cmds

# TODO: add as method to Comp via decorator?